### ISSUE TITLE
Translocation block check

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#64] opened 2021-04-09 16:03 UTC
![2021-04-09_17 01 59](https://user-images.githubusercontent.com/64480337/114208411-59a22300-9955-11eb-96d2-c281285d5c21.png)
The shown setup won't translocate because the fencegate isn't included in the "translocatable" blocks list. This list is also missing several other no-hitbox blocks. This may cause problems in some guns.

**Comment by TylerS1066** [comment] 2021-04-09 16:49
Duplicate of #52 , please report to there.

**Closed by TylerS1066** 2021-04-09 16:49 UTC
