### ISSUE TITLE
Combat tracking doesn't work.

### ISSUE THREAD

**Issue by goodroach** [TylerS1066/Movecraft-Combat#89] opened 2022-01-26 09:00 UTC
**Description**:
Whenever someone else sinks my ship, the message says that I sunk the ship instead of the person who actually sunk me. I tested this using various ships, and with different weapons. They all end up with the message saying that I sunk myself.

**What it should look like**:
If an enemy pilot sinks me, then they should get the credit for the kill on the kill feed. 

**Versions**
Movecraft 8 a6 
Movecraft Combat for Movecraft 8 a6
Version: 1.16.5
Java version: 16

**Comment by TylerS1066** [comment] 2022-01-26 16:13
Can you give us the exact Movecraft-Combat version (or dev build)?  If it's not `2.0.0-a.5`, please try and see if it fixes the problem.

If that doesn't work, can you post the damage tracking portion of your config?  On the AP servers we have all damage types enabled and it seems to be working ok for 1.14.4, albeit you usually get credit for sinking yourself.

In addition, do you have Movecraft-Cannons loaded with Movecraft-Combat integration enabled?  If so, that may affect this result.

**Comment by goodroach** [comment] 2022-01-26 21:32
The exact version of the MCC is Movecraft-Combat 2.0.0-a.5. I haven't downloaded any dev builds on my servers since I updated.

I'll send the tracking portion here: 
```
Damage Tracking
EnableFireballTracking: true # Enable tracking and recording of fireballs (higher lag than other tracking methods)
EnableTNTTracking: true # Enable tracking and recording of TNT damage (please read the wiki page before enabling!)
EnableTorpedoTracking: true # Enable tracking and recording of Torpedo damage
DamageTimeout: 300 # Timeout for damages in seconds

```

I don't have movecraft-cannons either, so I'm not sure what's causing it.

**Comment by TylerS1066** [comment] 2022-01-26 21:41
Interesting, I'll have to look into this problem.

**Comment by TylerS1066** [comment] 2022-01-31 01:23
This has been fixed as of https://github.com/TylerS1066/Movecraft-Combat/commit/e293aa7816cf55bc6a0cdc2e5da81a79d4b92592, it looks like I reversed the cause and damager in the damage records.

**Closed by TylerS1066** 2022-01-31 01:23 UTC
